Exam Preparation/01_Exam Preparation/MyMusicApp/MyMusicApp/albums/urls.py
from django.urls import path, include
from MyMusicApp.albums import views

urlpatterns = [
    path('add/', views.AlbumCreateView.as_view(), name='add-album'),
    path('<int:id>/', include([
        path('edit/', views.AlbumEditView.as_view(), name='album-edit'),
        path('details/', views.AlbumDetailsView.as_view(), name='album-details'),
        path('delete/', views.AlbumDeleteView.as_view(), name='album-delete'),
    ]))
]

Exam Preparation/01_Exam Preparation/MyMusicApp/MyMusicApp/common/urls.py
from django.urls import path
from MyMusicApp.common.views import HomePage

urlpatterns = [
    path('', HomePage.as_view(), name='home'),
]

Exam Preparation/01_Exam Preparation/MyMusicApp/MyMusicApp/profiles/urls.py
from django.urls import path
from MyMusicApp.profiles import views

urlpatterns = [
    path('details/', views.ProfileDetailView.as_view(), name='profile-details'),
    path('delete/', views.ProfileDeleteView.as_view(), name='profile-delete'),
]

Exam Preparation/01_Exam Preparation/MyMusicApp/MyMusicApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MyMusicApp.common.urls')),
    path('album/', include('MyMusicApp.albums.urls')),
    path('profile/', include('MyMusicApp.profiles.urls')),
]

Exam Preparation/01_Exam Preparation/MyMusicApp/MyMusicApp/albums/models.py
from django.core.validators import MinValueValidator
from django.db import models

from MyMusicApp.albums.choices import GenreChoices


# Create your models here.
class Album(models.Model):
    album_name = models.CharField(
        max_length=50,
        unique=True,
    )

    artist = models.CharField(
        max_length=30,
    )

    genre = models.CharField(
        max_length=30,
        choices=GenreChoices.choices
    )

    description = models.TextField(
        null=True,
        blank=True,
    )

    image_url = models.URLField()

    price = models.FloatField(
        validators=[
            MinValueValidator(0.0),
        ]
    )

    owner = models.ForeignKey(
        to="profiles.Profile",
        on_delete=models.CASCADE,
        related_name="albums",
    )

Exam Preparation/01_Exam Preparation/MyMusicApp/MyMusicApp/common/models.py
from django.db import models

# Create your models here.

Exam Preparation/01_Exam Preparation/MyMusicApp/MyMusicApp/profiles/models.py
from django.core.validators import MinLengthValidator
from django.db import models
from MyMusicApp.profiles.validators import NumericAlphaValidator


class Profile(models.Model):
    username = models.CharField(
        max_length=15,
        validators=[
            NumericAlphaValidator(),
            MinLengthValidator(3)
        ]
    )

    email = models.EmailField()

    age = models.PositiveIntegerField(
        null=True,
        blank=True,
    )

Exam Preparation/01_Exam Preparation/MyMusicApp/MyMusicApp/albums/forms.py
from django import forms
from MyMusicApp.albums.models import Album
from MyMusicApp.mixins import PlaceholderMixin, ReadOnlyMixin


class AlbumBaseForm(forms.ModelForm):
    class Meta:
        model = Album
        exclude = ('owner', )


class AlbumCreateForm(PlaceholderMixin, AlbumBaseForm):
    pass


class AlbumEditForm(PlaceholderMixin, AlbumBaseForm):
    pass


class AlbumDeleteForm(ReadOnlyMixin, AlbumBaseForm):
    read_only_fields = ['album_name', 'artist', 'genre', 'price', 'description']

Exam Preparation/01_Exam Preparation/MyMusicApp/MyMusicApp/profiles/forms.py
from django import forms

from MyMusicApp.mixins import PlaceholderMixin
from MyMusicApp.profiles.models import Profile


class ProfileBaseForm(PlaceholderMixin, forms.ModelForm):
    class Meta:
        model = Profile
        fields = "__all__"


class ProfileCreateForm(ProfileBaseForm):
    pass

Exam Preparation/01_Exam Preparation/MyMusicApp/MyMusicApp/albums/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DetailView, DeleteView

from MyMusicApp.albums.forms import AlbumCreateForm, AlbumEditForm, AlbumDeleteForm
from MyMusicApp.albums.models import Album
from MyMusicApp.utils import get_user_obj


class AlbumCreateView(CreateView):
    model = Album
    form_class = AlbumCreateForm
    template_name = 'album/album-add.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.instance.owner = get_user_obj()
        return super().form_valid(form)


class AlbumEditView(UpdateView):
    model = Album
    form_class = AlbumEditForm
    pk_url_kwarg = 'id'
    template_name = 'album/album-edit.html'
    success_url = reverse_lazy('home')


class AlbumDeleteView(DeleteView):
    model = Album
    form_class = AlbumDeleteForm
    pk_url_kwarg = 'id'
    template_name = 'album/album-delete.html'
    success_url = reverse_lazy('home')

    def get_initial(self):
        return self.object.__dict__

    def form_invalid(self, form):
        return self.form_valid(form)


class AlbumDetailsView(DetailView):
    model = Album
    pk_url_kwarg = 'id'
    template_name = 'album/album-details.html'

Exam Preparation/01_Exam Preparation/MyMusicApp/MyMusicApp/common/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import BaseFormView

from MyMusicApp.albums.models import Album
from MyMusicApp.profiles.forms import ProfileCreateForm
from MyMusicApp.utils import get_user_obj


class HomePage(ListView, BaseFormView):
    model = Album
    form_class = ProfileCreateForm
    success_url = reverse_lazy('home')

    def get_template_names(self):
        profile = get_user_obj()  # None or QuerySet

        if profile:
            return ['profile/home-with-profile.html']

        return ['profile/home-no-profile.html']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)  # Call the base method to get existing context
        context['albums'] = self.get_queryset()  # Add albums to context
        context['form'] = self.get_form()  # Include the profile creation form
        return context

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

Exam Preparation/01_Exam Preparation/MyMusicApp/MyMusicApp/profiles/views.py
from django.urls import reverse_lazy
from django.views.generic import DetailView, DeleteView

from MyMusicApp.utils import get_user_obj


class ProfileDetailView(DetailView):
    template_name = 'profile/profile-details.html'

    def get_object(self, queryset=None):
        return get_user_obj()


class ProfileDeleteView(DeleteView):
    template_name = 'profile/profile-delete.html'
    success_url = reverse_lazy('home')

    def get_object(self, queryset=None):
        return get_user_obj()

Exam Preparation/01_Exam Preparation/MyMusicApp/templates/album/album-add.html
{% extends 'base.html' %}

{% block content %}
    <section class="createPage">
        <form method="post">
            <fieldset>
                <legend>Add Album</legend>
                <div class="container">
                    {{ form }}
                    {% csrf_token %}
                    <!-- Button for Adding Album -->
                    <button class="add-album" type="submit">Add New Album</button>
                </div>
            </fieldset>
        </form>
    </section>
{% endblock %}

Exam Preparation/01_Exam Preparation/MyMusicApp/templates/album/album-delete.html
{% extends 'base.html' %}

{% block content %}
    <section class="editPage">
        <form method="post">
            <fieldset>
                <legend>Delete Album</legend>
                <div class="container">
                    {{ form }}
                    {% csrf_token %}
                    <button class="delete-album" type="submit">Delete Album</button>
                </div>
            </fieldset>
        </form>
    </section>
{% endblock %}

Exam Preparation/01_Exam Preparation/MyMusicApp/templates/album/album-details.html
{% extends 'base.html' %}

{% block content %}
    <section id="detailsPage">
        <div class="wrapper">
            <div class="albumCover">
                <!-- Album Image -->
                <img src="{{ album.image_url }}" alt="Cover Image"/>
            </div>

            <div class="albumInfo">
                <div class="albumText">
                    <!-- Album Info -->
                    <h1>Name: {{ album.album_name }}</h1>
                    <h3>Artist: {{ album.artist }}</h3>
                    <h4>Genre: {{ album.genre }}</h4>
                    <h4>Price: ${{ album.price|floatformat:2 }}</h4>
                    {% if album.description %}
                        <p>
                            Description: {{ album.description }}
                        </p>
                    {% endif %}
                </div>

                <div class="actionBtn">
                    <!-- Album Buttons -->
                    <a href="{% url 'album-edit' album.pk %}" class="edit">Edit</a>
                    <a href="{% url 'album-delete' album.pk %}" class="remove">Delete</a>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

Exam Preparation/01_Exam Preparation/MyMusicApp/templates/album/album-edit.html
{% extends 'base.html' %}

{% block content %}
    <section class="editPage">
        <form method="post">
            <fieldset>
                <legend>Edit Album</legend>
                <div class="container">
                    {{ form }}
                    {% csrf_token %}
                    <!-- Button for Editing Album -->
                    <button class="edit-album" type="submit">Edit Album</button>
                </div>
            </fieldset>
        </form>
    </section>
{% endblock %}

Exam Preparation/01_Exam Preparation/MyMusicApp/templates/base.html
{% load get_user %}
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>My Music App</title>
    <!-- Static Load -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>

<body>
<div id="box">
    <!-- Navigation Bar -->
    <header>
        <nav>
            <img src="{% static 'images/headphones.png' %}" alt="headphones"/>
            <a href="{% url 'home' %}">Home</a>
            <ul></ul>
            {% get_user as profile %}
            {% if profile %}
                <ul>
                    <!--Only for user with created profile-->
                    <li><a href="{% url 'add-album' %}">Create Album</a></li>
                    <li><a href="{% url 'profile-details' %}">Profile</a></li>
                </ul>
            {% endif %}
        </nav>
    </header>
    <!-- End Navigation Bar -->
    {% block content %}
    {% endblock %}
    <!-- Footer -->
    <footer>
        <div>&copy;SoftUni Team 2024. All rights reserved.</div>
    </footer>
    <!-- End Footer -->
</div>
</body>
</html>

Exam Preparation/01_Exam Preparation/MyMusicApp/templates/profile/home-no-profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container-inline">
        <section id="welcomePage">
            <div id="welcome-message">
                <h1>Welcome to</h1>
                <h1>My Music App!</h1>
            </div>
            <div class="music-img">
                <img src="{% static 'images/musicIcons.webp' %}" alt="music-icon"/>
            </div>
        </section>

        <!-- Registration -->
        <section id="registerPage">
            <form method="post">
                <fieldset>
                    <legend>Profile</legend>
                    {% csrf_token %}
                    {{ form }}
                    <button type="submit" class="register">Enter</button>
                </fieldset>
            </form>
        </section>
    </div>
{% endblock %}

Exam Preparation/01_Exam Preparation/MyMusicApp/templates/profile/home-with-profile.html
{% extends 'base.html' %}

{% block content %}
    <section id="catalogPage">
        {% if album_list %}
            <h1>All Albums</h1>
        {% else %}
            <p>No Albums in Catalog!</p>
        {% endif %}

        {% for album in album_list %}
            <div class="card-box">
                <img src="{{ album.image_url }}" alt="Cover Image"/>
                <div>
                    <div class="text-center">
                        <p class="name">Name: {{ album.album_name }}</p>
                        <p class="artist">Artist: {{ album.artist }}</p>
                        <p class="genre">Genre: {{ album.genre }}</p>
                        <p class="price">Price: ${{ album.price|floatformat:2 }}</p>
                    </div>
                    <div class="btn-group">
                        <a href="{% url 'album-details' album.pk %}">Details</a>
                    </div>
                </div>
            </div>
        {% endfor %}
        <!-- End First Card-Box in catalog -->
    
    </section>
{% endblock %}

Exam Preparation/01_Exam Preparation/MyMusicApp/templates/profile/profile-delete.html
{% extends 'base.html' %}

{% block content %}
    <section id="detailsPage">
        <div class="wrapper">
            <div class="profileText">
                <!-- Delete Profile Form -->
                <h1>Are you sure you want to delete your profile?</h1>
                <form method="post">
                    {% csrf_token %}
                    <button class="delete-profile" type="submit">Delete</button>
                </form>
                <!-- End Delete Profile Form -->
            </div>
        </div>
    </section>
{% endblock %}

Exam Preparation/01_Exam Preparation/MyMusicApp/templates/profile/profile-details.html
{% extends 'base.html' %}

{% block content %}
    <section id="detailsPage">
        <div class="wrapper">
            <div class="profilePage">
                <img
                        src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png"
                        alt="Profile Image"
                />
            </div>

            <div class="profileText">
                <!-- Profile Info -->
                <h1>Username: {{ object.username }}</h1>
                <h1>Email: {{ object.email }}</h1>
                <h1>Age: {{ object.age }}</h1>
                <h1>Albums: {{ object.albums.count }}</h1>
            </div>

            <div class="actionBtn">
                <!-- Button for Deleting the Profile -->
                <a href="{% url 'profile-delete' %}" class="remove">Delete</a>
            </div>
        </div>
    </section>
{% endblock %}